### ISSUE TITLE
Create SilentEchoValidator component

### ISSUE THREAD

**Issue by jkelvie** [bespoken/silent-echo-sdk#5]
# Overview
The validator will take a series of tests and execute them using the SilentEcho service. 

## Test Structure
A test sequence is made up of an array of ValidatorTest objects.

ValidatorTest has the following properties:
* input
* comparison
* expectedTranscript [optional]
* expectedStreamURL [optional]

For now, the only value for comparison is "contains".

## Signature
The signature of the Validator will require the following methods:
1) Constructor with token
The token is used for accessing the Silent Echo virtual device
2) execute(tests: Array<ValidatorTest>): ValidatorResult
An array of tests - each sequence in the script should be turned into an array of simple objects that describe the tests. A Validator test would contain properties for:

## Test Output
Test output will be in well structured array of objects, one for each test. Each test result object will have:
1) The sequence number of the tests
2) The index number of the test within the sequence
3) The absolute index of the test within the file
4) The input of the test
5) The actual output of the test (entire payload - transcript, transcriptURL, and streamURL)
6) The result of the test (success or failure)

Additionally, there should be a overall result object (ValidatorResult) that contains:
1) Success or failure of the tests overall (failure if any test fails)

## Other Notes
The Validator objects are part of the definitions for the silent-echo-sdk library, and should be exported as part of Index.ts file.

**Comment by chris-ramon** [comment]
closing this one, addressed via: https://github.com/bespoken/silent-echo-sdk/pull/12, https://github.com/bespoken/silent-echo-sdk/pull/13, https://github.com/bespoken/silent-echo-sdk/pull/14, https://github.com/bespoken/silent-echo-sdk/pull/15
