### ISSUE TITLE
Create SilentEchoScript component

### ISSUE THREAD

**Issue by jkelvie** [bespoken/silent-echo-sdk#6]
# Overview
The SilentEchoScript component provides an easy way to interact with the SilentEchoValidator. It will take a simple text file that describes a series of tests and execute them using the SilentEchoValidator service.

## Format
The format of a Validator Script will be:
```
<Input>: <ExpectedOutput>
<Input>: <ExpectedOutput>

<Input>: <ExpectedOutput>
...
```

An input is a phrase in quotes:
"Hi"
"Hello There"

An expected output is either a phrase or URL:
"Hi"
http://test.com/my/audio/file.mp3

A blank line represents a new sequence of tests. Tests that are part of a sequence will be run as part of a single session. 

## Example
```
"Open We Study Billionaires": "Welcome"
"Play": http://first.com/file.mp3
"Next": http://second.com/file.mp3

"Open We Study Billionaires": "Hi"
```
In this test, the skill We Study Billionaires will be issued the three commands "Open", "Play" and "next" in quick succession.

The second "Open" will be sent after a pause. It will act after the first session has concluded.

The exact duration of the pause between sessions needs to be determined - we do not have precise session-handling at this point. I would suggest starting with a value of 10 seconds.

## Test Rules
All tests will use an implied "contains" match. If the actual output contains the expected output, it will be considered a match.

URL comparisons will be performed against the Stream URL.

All comparisons are case-insensitive (note: this is a feature of the Validator - nothing needs to be done by the Script component to implement this).

## Test Output
The test output will be the ValidatorResult object from the SilentEchoValidator

## Signature
The signature of the SilentEchoScript will require the following methods:
1) Constructor with token
The token is used for accessing the Silent Echo virtual device

2) execute(scriptContents: string)
The contents of a test to execute

3) validate(scriptContents: string): (string | undefined)
Run this to ensure that the test script is in a valid format. Undefined means it is valid, a string contains the error message, if there is an error.

## Other Notes
The Validator objects are part of the definitions for the silent-echo-sdk library, and should be exported as part of Index.ts file.

**Comment by chris-ramon** [comment]
closing this one, addressed via: https://github.com/bespoken/silent-echo-sdk/pull/12, https://github.com/bespoken/silent-echo-sdk/pull/13, https://github.com/bespoken/silent-echo-sdk/pull/14, https://github.com/bespoken/silent-echo-sdk/pull/15
