### ISSUE TITLE
Add HTML output for SilentEchoScript

### ISSUE THREAD

**Issue by jkelvie** [bespoken/silent-echo-sdk#7]
## Overview
Create prettified HTML output as part of running a SilentEchoScript.

It should be broken down by sequence, with each test within the sequence listed. 

Tests that are a success should be output with a checkmark and a green font.
Tests that are a failure should be output with an "X" mark and a red font.

## Example
For the following input script:
```
"Open We Study Billionaires": "Welcome"
"Play": http://first.com/file.mp3
"Next": http://second.com/file.mp3

"Open We Study Billionaires": "Hi"
```

Output:
Overall:
<red>4 tests, 3 succeeded, 1 failed</red>

Time:
7/5/2017 11:02:00 UTC

**Sequence 1:**

Result | Input | Expected | Actual
------ | ----- | -------- | ------
✔ | "Open We Study Billionaires" | "Welcome" | "Welcome to We Study Billionaires"
✖ | "Play" | http://first.com/file.mp3 | http://first.com/file2.mp3
✔ | "Next" | http://second.com/file.mp3 | http://second.com/file.mp3

**Sequence 2:**

Result | Input | Expected | Actual
------ | ----- | -------- | ------
✔ | "Open We Study Billionaires" | "Welcome" | "Welcome to We Study Billionaires"

Note - this is a low-fidelity mockup - please feel free to suggest improvements for the real UI.

## Signature
The Validator should have a method "prettifyAsHTML(result: ValidatorResult): string"
The method takes the validator result and returns the HTML string.

**Comment by chris-ramon** [comment]
closing this one, addressed via: https://github.com/bespoken/silent-echo-sdk/pull/12, https://github.com/bespoken/silent-echo-sdk/pull/13, https://github.com/bespoken/silent-echo-sdk/pull/14, https://github.com/bespoken/silent-echo-sdk/pull/15
